
name: Build uLaunch

on: [push, pull_request]

jobs:
  uLaunch:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Update packages and install Python
      run: |
        sudo -n apt-get update
        sudo -n apt-get upgrade -y patch autoconf automake diffutils pkgconf fakeroot git maven file tar bzip2 zstd python3 python3-pip python-is-python3
        python -m pip install requests
        sudo -n dkp-pacman --noconfirm -U \
          "https://wii.leseratte10.de/devkitPro/other-stuff/dkp-toolchain-vars-1.0.2-1-any.pkg.tar.xz"

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"
    
    - name: Prepare master libnx
      run: |
        git clone https://github.com/switchbrew/libnx
        make -C libnx/
        cp -r libnx/nx/external/bsd/include libnx/nx
    
    - name: Compile
      run: |
        make -j$(nproc) LIBNX=$PWD/libnx/nx/ usystem uloader umenu umanager
        zip -r SdOut.zip SdOut
        
    - uses: actions/upload-artifact@master
      with:
        name: SdOut
        path: SdOut.zip
        if-no-files-found: error
